### ISSUE TITLE
Getting an FetchError on use

### ISSUE THREAD

**Issue by rjbprime** [MrPrimate/ddb-proxy#27]
Not sure what is going on. I am using FoundryVTT v10.303, dnd5e v2.2.2, and ddb-importer v3.4.57, with ddb-proxy v0.0.24, and am now getting the below error.

```
D:\Git 2023\ddb-proxy>node index.js
DDB Proxy started on :3000
Retrieving ddb config
undefined
Error retrieving DDB Config
FetchError: invalid json response body at https://www.dndbeyond.com/api/config/json reason: Unexpected token < in JSON at position 0
    at D:\Git 2023\ddb-proxy\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
FetchError: invalid json response body at https://www.dndbeyond.com/api/config/json reason: Unexpected token < in JSON at position 0
    at D:\Git 2023\ddb-proxy\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
```

**Comment by MrPrimate** [comment]
This can sometimes happen, ddb-importer should fall back to using a default fallback config though.

**Comment by myrheimb** [comment]
I have the same error and it appears that dndbeyond is blocking it.
Here's the message from the response below:
`Access to this page has been denied because we believe you are using automation tools to browse the website.`

Full reponse:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Access to this page has been denied.</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            font-family: \'Open Sans\', sans-serif;
            color: #000;
        }

        a {
            color: #c5c5c5;
            text-decoration: none;
        }

        .container {
            align-items: center;
            display: flex;
            flex: 1;
            justify-content: space-between;
            flex-direction: column;
            height: 100%;
        }

        .container>div {
            width: 100%;
            display: flex;
            justify-content: center;
        }

        .container>div>div {
            display: flex;
            width: 80%;
        }

        .customer-logo-wrapper {
            padding-top: 2rem;
            flex-grow: 0;
            background-color: #fff;
            visibility: visible;
        }

        .customer-logo {
            border-bottom: 1px solid #000;
        }

        .customer-logo>img {
            padding-bottom: 1rem;
            max-height: 50px;
            max-width: 100%;
        }

        .page-title-wrapper {
            flex-grow: 2;
        }

        .page-title {
            flex-direction: column-reverse;
        }

        .content-wrapper {
            flex-grow: 5;
        }

        .content {
            flex-direction: column;
        }

        .page-footer-wrapper {
            align-items: center;
            flex-grow: 0.2;
            background-color: #000;
            color: #c5c5c5;
            font-size: 70%;
        }

        @media (min-width: 768px) {

            html,
            body {
                height: 100%;
            }
        }
    </style> <!-- Custom CSS -->
    <link href="https://media-waterdeep.cursecdn.com/attachments/px.css" rel="stylesheet">
</head>

<body>
    <section class="container">
        <div class="customer-logo-wrapper">
            <div class="customer-logo"> <img
                    src="https://www.dndbeyond.com/content/skins/Waterdeep/images/dnd-beyond-logo-black.svg"
                    alt="Logo" /> </div>
        </div>
        <div class="page-title-wrapper">
            <div class="page-title">
                <h1>Please verify you are a human</h1>
            </div>
        </div>
        <div class="content-wrapper">
            <div class="content">
                <div id="px-captcha"> </div>
                <p> Access to this page has been denied because we believe you are using automation tools to browse the
                    website. </p>
                <p> This may happen as a result of the following: </p>
                <ul>
                    <li> Javascript is disabled or blocked by an extension (ad blockers for example) </li>
                    <li> Your browser does not support cookies </li>
                </ul>
                <p> Please make sure that Javascript and cookies are enabled on your browser and that you are not
                    blocking them from loading. </p>
                <p> Reference ID: #b96a2dd3-464e-11ee-bc2d-775871586572 </p>
            </div>
        </div>
        <div class="page-footer-wrapper">
            <div class="page-footer">
                <p> Powered by <a href="https://www.perimeterx.com/whywasiblocked">PerimeterX</a> , Inc. </p>
            </div>
        </div>
    </section> <!-- Px -->
    <script> window._pxAppId = \'PXcNj12cyX\'; window._pxJsClientSrc = \'/cNj12cyX/init.js\'; window._pxFirstPartyEnabled = true; window._pxVid = \'\'; window._pxUuid = \'b96a2dd3-464e-11ee-bc2d-775871586572\'; window._pxHostUrl = \'/cNj12cyX/xhr\'; </script>
    <script> var s = document.createElement(\'script\'); s.src = \'/cNj12cyX/captcha/captcha.js?a=c&u=b96a2dd3-464e-11ee-bc2d-775871586572&v=&m=0\'; var p = document.getElementsByTagName(\'head\')[0]; p.insertBefore(s, null); if (true ){s.onerror = function () {s = document.createElement(\'script\'); var suffixIndex = \'/cNj12cyX/captcha/captcha.js?a=c&u=b96a2dd3-464e-11ee-bc2d-775871586572&v=&m=0\'.indexOf(\'/captcha.js\'); var temperedBlockScript = \'/cNj12cyX/captcha/captcha.js?a=c&u=b96a2dd3-464e-11ee-bc2d-775871586572&v=&m=0\'.substring(suffixIndex); s.src = \'//captcha.px-cdn.net/PXcNj12cyX\' + temperedBlockScript; p.parentNode.insertBefore(s, p);};}</script>
    <!-- Custom Script -->
</body>

</html>
```

**Comment by pykekaisora** [comment]
For me, it works for Items, Spell and adventures. Only monsters couldn't work for me. I use cloudflare tunnel because it handles proxies for me.

```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>ddb-proxy.domain.com | 524: A timeout occurred</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">A timeout occurred</span>
              <span class="code-label">Error code 524</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_524&utm_campaign=ddb-proxy.domain.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2024-12-24 08:31:13 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_524&utm_campaign=ddb-proxy.domain.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Singapore</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_524&utm_campaign=ddb-proxy.domain.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">ddb-proxy.domain.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The origin web server timed out responding to this request.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
      <p><span>The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524">Additional troubleshooting information here.</a></p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8f6f3969ab9c5fe4</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">180.74.69.198</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_524&utm_campaign=ddb-proxy.domain.com" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>
```

**Comment by pykekaisora** [comment]
Nvm, It's cloudflare Tunnel's Timeout.
